name: Create Prediction CSV

on:
  workflow_run:
      workflows: ["Build and deploy Python app to Google Cloud - Pace Risk Map"]
      types:
        - completed
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_analysis.txt

    - name: Run script
      run: |
        python crea_pred_csv.py
    - name: Add and commit
      uses: EndBug/add-and-commit@v9
      with:
        author_name: GitHub Actions
        author_email: 41898282+github-actions[bot]@users.noreply.github.com
        github_token: ${{ secrets.GITHUB_TOKEN }}
        message: "chore: Create Tweets"
        add: "*.csv"
