# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Google Cloud - Pace Risk Map

on:
  workflow_run:
      workflows: ["Create PDF"]
      types:
        - completed
  workflow_dispatch:

jobs:
  deploy:
    name: Deploying Risk Map
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2 # Updated to a supported version
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }} # Updated key name
  
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '461.0.0'  # Replace with the version you want
          project_id: pace-risk-map


      - name: Building (🏗)
        run: |-
          gcloud builds submit \
            --tag gcr.io/pace-risk-map/pace-risk-map

      # Setup gcloud CLI
      - name: Deploy (🚀)
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service:  pace-risk-map
          image: gcr.io/pace-risk-map/pace-risk-map
          region: us-east1
          credentials: ${{ secrets.GCP_SA_KEY_JSON }}
          project_id: pace-risk-map
